FROM python:3.11.6-alpine3.18

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir requests yt-dlp
RUN apk add --no-cache ffmpeg
WORKDIR /app
COPY bin/downloader.py .
RUN chmod a+x downloader.py
CMD /app/downloader.py
